--MEMBER Å×ÀÌ÷ם
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(100)
    , PWD VARCHAR2(100)
    , NICK VARCHAR2(100)
    , ENROLL_DATE TIMESTAMP
    , QUIT_YN CHAR(1)
);

SELECT * FROM MEMBER WHERE ID = 'admin' AND PWD = '1234';

